vyos:
  hosts:
    10.0.17.200:
      hostname: fw-blue1
      lan_ip: 10.0.5.2
      lan: 10.0.5.0/24
      mac: 00:50:56:9b:d5:22
      shared_network: blue1
      dhcp_name_server: 10.0.5.5
      dhcp_domain: blue1.local

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: network_cli
    ansible_network_os: vyos
    ansible_user: vyos
