windows:
  hosts:
  children:
    domain_controller:
      hosts:
        10.0.5.5:
          hostname: dc-blue1
    file_server:
      hosts:
        10.0.5.13:
          hostname: fs-blue1
    workstation:
      hosts:
        10.0.5.x # This would be a DHCP-assigned IP
          hostname: wks-blue1

  vars:
    ansible_user: deployer
    ansible_shell_type: powershell
