# Post provisioning for rocky1-3
- name: configure rocky
  hosts: rocky
  tasks:
  - name: create ssh dir if nonexistent
    file:
      path: "/home/{{ ansible_user }}/.ssh"
      state: directory
      mode: '0700'

  - name: create authorized_keys file
    file:
      path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
      state: touch
      mode: '0600'

  - name: copy public key to authorized_keys
    blockinfile:
      dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
      block: "{{ public_key }}"

  - name: create sudoer drop-in file
    file:
      path: "/etc/sudoers.d/480"
      state: touch
      mode: '0400'
    become: yes

  - name: create drop-in entry
    blockinfile:
      dest: "/etc/sudoers.d/480"
      block: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    become: yes

  - name: set hostname
    hostname:
      name: "{{ hostname }}"
    become: yes

  - name: add host to hosts file
    lineinfile:
      path: "/etc/hosts"
      line: "127.0.1.1 {{ hostname }}"
    become: yes

  - name: set static IPs
    nmcli:
      conn_name: "{{ device }}"
      ip4: "{{ lan_ip }}/{{ prefix }}"
      gw4: "{{ gateway }}"
      state: present
      type: ethernet
      dns4:
        - "{{ name_server }}"
        - "{{ gateway }}"
      method4: manual
    become: yes

  - name: bounce the box
    shell: "sleep 5 && shutdown -r"
    become: yes
    async: 1
    poll: 0
