- name: adds deployment
  hosts: windows
  vars_prompt:
    - name: adminpass
      prompt: "Please enter your local admin password"
      private: yes

  tasks:
    - name: change admin pass
      win_user:
        name: Administrator
        password: "{{ adminpass }}"
        update_password: always

    - name: set hostname
      win_hostname:
        name: "{{ hostname }}"
      register: hostreboot

    - name: reboot to set hostname
      win_reboot:
      when: hostreboot.reboot_required

    - name: ad feature
      win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: yes

    - name: forest creation
      win_domain:
        dns_domain_name: blue.local
        safe_mode_password: "{{ adminpass }}"
      register: domain_install

    - name: reboot after domain install
      win_reboot:
      when: domain_install.reboot_required

    - name: elevate deployer
      community.windows.win_domain_user:
        name: deployer
        state: present
        groups_action: add
        groups:
          - Domain Admins
          - Enterprise Admins

    - name: dns forwarder
      win_shell: Add-DnsServerForwarder -IPAddress 10.0.5.2

    - name: ou structure
      win_shell: |
        Import-Module ActiveDirectory
        New-ADOrganizationalUnit -Name blue1 -Path "DC=BLUE,DC=local"
        New-ADOrganizationalUnit -Name Accounts -Path "OU=blue1,DC=BLUE,DC=local"
        New-ADOrganizationalUnit -Name Groups -Path "OU=blue1,OU=Accounts,DC=BLUE,DC=local"
        New-ADOrganizationalUnit -Name Computers -Path "OU=blue1,DC=BLUE,DC=local"
        New-ADOrganizationalUnit -Name Servers -Path "OU=blue1,OU=Computers,DC=BLUE,DC=local"
        New-ADOrganizationalUnit -Name Workstations -Path "OU=blue1,OU=Computers,DC=BLUE,DC=local"
