- name: wks domain join
  hosts: workstation
  vars_prompt:
  - name: admin pass
    prompt: "Please enter the admin password"
    private: true
  tasks:
  - name: join wks to domain
    win_domain_membership:
      dns_domain_name: blue.local
      hostname: "{{ hostname }}"
      domain_admin_user: "{{ domain_admin }}"
      domain_admin_password: "{{ domain_password }}"
      state: domain
      domain_ou_path: "OU=Computers,OU=blue1,DC=BLUE,DC=local"
    register: domain_join

  - name: reboot after domain join
    win_reboot:
    when: domain_join.reboot_required
